on:
  push:
    branches:
      - main

env:
  REGION: "sa-east-1"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Criar pacote para deploy
        run: |
          zip -r deploy.zip . -x '*.git*' -x 'node_modules/*' -x 'tests/*'

      - name: Deploy para Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: projetoAprendizUrucania
          environment_name: ProjetoAprendizUrucania-env
          region: ${{ env.REGION }}
          version_label: ${{ github.ref_name }}-${{ github.run_number }}-${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true
