name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main # ou a branch de sua preferência

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'  # Região do seu Elastic Beanstalk, altere conforme necessário

      - name: Install dependencies
        run: |
          # Caso esteja usando Node.js, ajuste conforme sua necessidade
          npm install

      - name: Build the application
        run: |
          # Comandos necessários para compilar ou empacotar sua aplicação
          npm run build

      - name: Create zip file for deployment
        run: |
          # Cria um arquivo ZIP da sua aplicação
          zip -r deploy.zip .

      - name: Deploy to AWS Elastic Beanstalk
        run: |
          # Subir o arquivo zip para o Elastic Beanstalk
          aws elasticbeanstalk create-application-version \
            --application-name YourApplicationName \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket="your-bucket-name",S3Key="deploy.zip"
          
          # Atualizar o ambiente do Elastic Beanstalk
          aws elasticbeanstalk update-environment \
            --environment-name YourEnvironmentName \
            --version-label ${{ github.sha }}
